extends:
  - eslint:recommended
env:
  es6: true
  browser: true
parserOptions:
  ecmaVersion: latest
  sourceType: module
  allowImportExportEverywhere: true
rules:
  indent:
    - warn
    - 2
  semi:
    - warn
    - never
  quotes:
    - warn
    - single
