extends:
  - eslint:recommended
env:
  es6: true
parserOptions:
  ecmaVersion: latest
  sourceType: module
  allowImportExportEverywhere: true
rules:
  semi:
    - warn
    - never
  quotes:
    - warn
    - single
