[package]
name = "flashcards-basic"
version = "0.1.0"
authors = ["Alexander Welshtein <alexanderwelshtein@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "4.0.0-beta.8"
actix-files = "0.6.0-beta.6"
tokio-postgres = "0.7.2"
deadpool-postgres = "0.9.0"
juniper = "0.15.7"